### ISSUE TITLE
Show neighborhoods that a route itinerary goes to

### ISSUE THREAD

**Issue by elliottwilliams** [propershark/proper#2]
I propose that we should show neighboorhoods or local landmarks that a particular route is headed towards. This information is useful in addition to a route or system map, because it allows for useful "heading towards" bylines on a list of routes or vehicles. For example:

```
Station: BUS123
============

Arrivals:
- Route 1A (#123)     in 2 min
  towards Downtown Lafayette
- Route 5B (#234)     in 5 min
  towards Wabash Landing, Happy Hollow
```

We can use MapKit's [reverse geocoder](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/UsingGeocoders/UsingGeocoders.html#//apple_ref/doc/uid/TP40009497-CH4-SW4) to obtain [`CLPlacemark`](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLPlacemark_class/index.html#//apple_ref/occ/instp/CLPlacemark/subThoroughfare)s from station lat-longs. They have a `subLocality` property, described as:

> "This property contains additional information, such as the name of the neighborhood or landmark associated with the placemark. It might also refer to a common name that is associated with the location."

An algorithm to produce these "heading towards" bylines would be:
1. Obtain placemarks for each station associated to a route.
2. Given a vehicle's current position on the itinerary, map upcoming stations to their `subLocality`.
3. Take the first n unique `subLocality`s and use them to construct the byline string.

Complications include:
- It takes n network requests to obtain these data for a route, where n = the number of stations associated. Thus, these data should be persisted or at least cached.
- Since this is a "sourcing data" task, I could see it better belonging to Shark (or another server-side producer). @faultyserver, what would you think about adding a `neighborhood` property to stations, and writing a source that uses a mapping API to get this information?

**Comment by faultyserver** [comment]
FWIW, TripSpark routes have this information in their `direction` sub-property (? whatever you want to call it, it's three levels down), but that's obviously not consist, guaranteed, nor exposed through Shark.

I can definitely see this as part of Shark (there is a [reverse geocoding gem](https://github.com/alexreisner/geocoder), but it seems to require Rack?). I was going to say that the feature is somewhat locale-dependent (and should thus be on the client side), but it occurred to me that the geocoding libraries probably take care of that already, and just return a locale-specific string.

Overall, I really like the idea, and would like to see it implemented soon, but I'm in the middle of 4-5 other parts of Shark right now, so I won't be able to handle this for a while. I don't think this has to be done server-side, but if you have time to work on this, feel free to implement it wherever you think is best.

**Comment by elliottwilliams** [comment]
Thanks! For now, let's move this to Shark. It's something I would feel comfortable working on (especially writing the source gem), but I need to concentrate of Proper until a few other core things are done :)

If we change our mind about implementing this client-side, we can re-open.
